-- CREACION DE LA BASE DE DATOS
DROP DATABASE IF EXISTS Pokedex;
CREATE DATABASE IF NOT EXISTS Pokedex;

USE Pokedex;

-- TABLA DE HABILIDADES DE POKEMON
CREATE TABLE IF NOT EXISTS Habilidades (
    Id_Habilidad INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Nombre_Habilidad VARCHAR(50) NOT NULL,
    Creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA DE SPRITES DE POKEMON
CREATE TABLE IF NOT EXISTS Sprites (
    Id_Sprite INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Descripcion_Sprite VARCHAR(100) NOT NULL,
    Url_Sprite VARCHAR(255) NOT NULL,
    Creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA DE INFORMACION DE POKEMON
CREATE TABLE IF NOT EXISTS Pokemones (
    Id_Pokemon INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Nombre_Pokemon VARCHAR(100) NOT NULL,
    Numero_Pokemon INTEGER NOT NULL,
    Id_Habilidad INTEGER NOT NULL,
    FOREIGN KEY (Id_Habilidad) REFERENCES Habilidades(Id_Habilidad) ON DELETE CASCADE,
    Id_Sprite INTEGER NOT NULL,
    FOREIGN KEY (Id_Sprite) REFERENCES Sprites(Id_Sprite) ON DELETE CASCADE,
    Creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(Numero_Pokemon),
    INDEX idx_nombre_pokemon (Nombre_Pokemon)
);

-- TABLA DE BITACORA DE MOVIMIENTOS
CREATE TABLE IF NOT EXISTS Bitacoras (
    Id_Bitacora INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Tabla VARCHAR(100) NOT NULL,
    Accion VARCHAR(100) NOT NULL,
    Registro_Id INT NULL,
    Fecha_Accion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);